services:

  # eureka_server:
  #   image: eureka-server
  #   container_name: eureka-server
  #   restart: on-failure
  #   ports:
  #     - "8761:8761"
  #   networks:
  #     - mynetwork

  cloud-config-servier:
    image: cloud-config-servier
    container_name: cloud-config-servier
    restart: no
    ports:
      - "8999:8999"
    networks: 
      - mynetwork
    volumes:
      # Link your local folder to the path defined in your YAML
      - /media/shreevardhan/E/projects/Microservices/config_properties/:/app/config_properties
    environment:
       # THIS IS THE MISSING KEY
       - SPRING_PROFILES_ACTIVE=native
networks:
  mynetwork:
    external: true
