server:
  port: 8999
spring:
  profiles:
    active:
    - native
  application:
    name: cloud-config-servier
  cloud:
    config:
      server:
        native:
          watch:
            enabled: true
          search-locations:
            -  file:/app/config_properties/